slug = "leadership"
name = "Labrador Leadership"
description = "The leadership team of Labrador."
create-oidc-clients = false

[[repos]]
name = "governance"
description = """
Definition and automation of the ScottyLabs Labrador GitHub
organization's governance model.
"""

[[membership]]
timeframe = "2026-2027"
leads = ["Yuxiang-Huang"]

[[membership.members]]
github-username = "Yuxiang-Huang"
title = "Head of Onboarding and Documentation"
