name = "Leadership"
description = "The Labrador leadership team."
create-oidc-clients = false

[[repos]]
name = "wiki"
description = "A central hub for ScottyLabs Labrador documentations"

[[membership]]
timeframe = "2026-2027"
leads = ["Yuxiang-Huang"]

[[membership.members]]
github-username = "Yuxiang-Huang"
title = "Head of Onboarding and Documentation"

[[membership.members]]
github-username = "dsnarne"
title = "Head of Innovation"
