[[rule]]
include = ["members/*.toml", "teams/*.toml"]

[[rule]]
include = ["members/*.toml"]

[rule.schema]
path = "./meta/schemas/member.schema.json"
enabled = true

[[rule]]
include = ["teams/*.toml"]

[rule.schema]
path = "./meta/schemas/team.schema.json"
enabled = true
