name: Sync

on:
  push:
    branches:
      - main

jobs:
  sync-codeowners:
    name: Sync Codeowners
    runs-on: ubuntu-latest

    env:
      SYNC_GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Sync Codeowners
        run: uv run --frozen --no-dev --group codeowners-synchronizer sync-codeowners
