name: Test

on:
  push:
    branches:
      - main
    paths:
      - "meta/**"

jobs:
  test-validator:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Test
        run: uv run --frozen --no-dev --group test test-validator
