# These validations are for commits that change the organizational structure.

name: Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-editorconfig:
    name: Validate EditorConfig Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install EditorConfig Checker
        uses: taiki-e/install-action@v2
        with:
          tool: editorconfig-checker
          fallback: none

      - name: Validate EditorConfig Compliance
        run: editorconfig-checker --exclude ^LICENSE

  validate-toml:
    name: Validate TOML Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Taplo
        uses: taiki-e/install-action@v2
        with:
          tool: taplo
          fallback: none

      - name: Validate TOML Formatting
        run: taplo fmt --check

      - name: Validate TOML Against Schemas
        run: taplo check

  validate-rules:
    name: Validate Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Validate Rules
        run: uv run --frozen --no-dev --group validator validate
